version: '3.8'

services:
  dbeaver:
    image: dbeaver/cloudbeaver:latest
    container_name: cloudbeaver
    restart: always
    ports:
      - "8978:8978"
    volumes:
      - cloudbeaver-data:/opt/cloudbeaver/workspace
    environment:
      - CB_ADMIN_NAME=xxxxxx
      - CB_ADMIN_PASSWORD=xxxxxx

volumes:
  cloudbeaver-data:
